# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  arch:
    runs-on: ubuntu-latest
    container: archlinux/base:latest
    steps:
      - uses: actions/checkout@v1
      - name: Update packages
        run: pacman -Syyu --noconfirm
      - name: Install required packages
        run: pacman -S --noconfirm git sudo
      - name: Install dotfiles
        run: ./install 
      - name: Add user
        run: useradd builduser -m
      - name: Add sudoer
        run: echo 'builduser ALL=(ALL) ALL' >> /etc/sudoers
      - name: Change password
        run: passwd -d builduser
